package model;

public enum TipoOutros {

	//Anel
	ANEL("Anel"),
	ACAOLIVRE("da Ação Livre"),
	ANDARAGUA("do Andar na Água"),
	ARIETE("do Aríete"),
	ARMAZENARMAGIA("de Armazenar Magia"),
	COMANDARELEMENTAIS("de Controlar Elementais"),
	INVISIBILIDADE("da Invisibilidade"),
	INVOCADOR("da Invocação"),
	NATACAO("da Natação"),
	PERICIA("da Perícia"),
		_ACR("(Acrobacia)"),
		_ADR("(Adestrar Animais)"),
		_ARC("(Arcanismo"),
		_ATL("(Atletismo)"),
		_ATU("(Atuação)"),
		_ENG("(Enganação)"),
		_FUR("(Furtividade)"),
		_HIS("(História)"),
		_INT("(Intimidação"),
		_INTU("(Intuição)"),
		_INV("(Investigação)"),
		_MED("(Medicina)"),
		_NAT("(Natureza"),
		_PER("(Percepção)"),
		_PERS("(Persuasão)"),
		_PRE("(Prestidigitação)"),
		_REL("(Religião)"),
		_SOB("(Sobrevivência)"),
	POTENCIAF("da Potência Física"),
	POTENCIAM("da Potência Mágica"),
	PROTECAO("da Proteção"),
	QUEDASUAVE("da Queda Suave"),
	RESISTENCIA("da Resistência"),
		_ACI("(Ácido)"),
		_FRI("(Frio)"),
		_FOG("(Fogo)"),
		_ENE("(Energia)"),
		_ELE("(Elétrico)"),
		_NEC("(Necrótico)"),
		_VEN("(Veneno)"),
		_PSI("(Psíquico)"),
		_RAD("(Radiante)"),
		_TRO("(Trovejante)"),
	RESISTENCIAF("da Resistência Física"),
	
	//Itens Maravilhosos
	JARROALQ("Jarro da Alquimia"),
	BASTAO("Bastão Imóvel"),
	BOLA("Bola de Cristal"),
	COLA("Cola Soberana"),
	CORDA("Corda de Escalada"),
	CUBO("Cubo do Portal"),
	DISPOSITIVO("Dispositivo de Kwalish"),
	FORTALEZA("Fortaleza Instantânea de Daern"),
	GEMAL("Gema da Luminosidade"),
	GEMAV("Gema da Visão"),
	GEMAE("Gema Elemental"),
	LANTERNA("Lanterna de Revelação"),
	MOCHILA("Mochila de Carga"),
	PEDRA("Pedra da Boa Sorte"),
	PEDRAI("Pedra Iônica"),
		PABS("(Absorção)"),
		PAGI("(Agilidade)"),
		PPRO("(Prontidão)"),
		PFOR("(Fortitude)"),
		PGAB("(Grande Absorção)"),
		PINT("(Intuição)"),
		PINTE("(Intelecto)"),
		PLID("(Liderança)"),
		PMAE("(Maestria)"),
		PPROT("(Proteção)"),
		PREG("(Regeneração)"),
		PARM("(Armazenamento)"),
		PFORC("(Força)"),
		PSUS("(Sustento)"),
	PEDRAM("Pedras de Mensagem"),
	SOLVENTE("Solvente Universal"),
	TAPETE("Tapete Voador"),
	
	//Poções
	POCAO("Poção"),
	AMIZADE("da Amizade Animal"),
	AUMENTAR("de Aumentar"),
	CLARIVIDENCIA("da Clarividência"),
	CURA("da Cura"),
	CURAC("da Cura Completa"),
	ENCOLHER("de Encolher"),
	VENENO("de Envenenamento"),
	ESCALAR("de Escalar"),
	FORMAG("da Forma Gasosa"),
	FORÇA("da Força do Gigante"),
	HEROISMO("do Heroísmo"),
	INVIS("da Invisibilidade"),
	INVUL("da Invulnerabilidade"),
	LERM("de Ler Mentes"),
	RESIST("da Resistência"),
	RESPIRAR("de Respirar na Água"),
	SOPRO("do Sopro de Fogo"),
	VEL("da Velocidade"),
	VIT("da Vitalidade"),
	VOO("do Vôo");
	
	private String descricao;

	TipoOutros(String descricao) {
		this.descricao = descricao;
	}

	public String getDescricao() {
		return descricao;
	}
}
